- name : Configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: Disable default nodejs package
    command: dnf module disable nodejs -y

  - name: Enable nodejs:20 package
    command: dnf module disable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:  #If i want this to work in all distributions then use package other wise yum or dnf (Redhat)
      name: nodejs
      state: latest  # latest version it will install

  - name: Create User 
    ansible.builtin.user: 
      name: expense

  - name: Create directory 
    ansible.builtin.file: 
      path: /app # where u want to create provide path
      state: directory # if we mention directory then only it will create a directory. otherwise by default file will be created

  - name: Download the file 
    ansible.builtin.get_url: 
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip  #provide the url, it will download the file
      dest: /tmp/backend.zip  # store the file here 

  - name: Unzip the file 
    ansible.builtin.unarchive: 
      src: /tmp/backend.zip
      dest: /app