- name : Configure MySQL db server
  hosts: db
  become: yes
  tasks:
  - name: Install Mysql Server
    debug:
      msg: "MYSQL server installed successfully"
    dnf:
      name: mysql-server
      state: latest
    

  - name: Start & enable Mysql Server
    debug:
      msg: "MYSQL server Started & enabled successfully"
    service:
      name: mysqld
      state: started
      enabled: yes
    
  