- name : Configure MySQL db server
  hosts: db
  become: yes
  tasks:
  - name: Install Mysql Server
    dnf:
      name: mysql-server
      state: latest
  
  - name: Print Success message
    debug:
      msg: "MYSQL server installed successfully"

  - name: Start & enable Mysql Server
    service:
      name: mysqld
      state: started
      enabled: yes
    
  - name: Print Success message
    debug:
      msg: "MYSQL server Started & enabled successfully"
  

  - name: Collect all info except settings and users by root
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.projexpenses78.online
      filter: version # how u check version of anything ansible --version/mysql-server --version. If it's shows something then success
    ignore_errors: true
    register: mysql_connection_output

  - name: Print Success message
    debug:
      msg: "Mysql connection output is: {{mysql_connection_output}}"